# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Work
    weight: 20
    hasChildren: true
  - parent: Work
    name: Projects
    url: projects/
  - parent: Work
    name: WorkBlogs
    url: work-blogs/
  - name: Daily
    url: daily/
    weight: 30
  - name: About me
    url: about-me/
    weight: 40

