# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Personal Blog
    local_business_type: ''
    org_name: 'Tande'
    description: 'Tande'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    button:
      enable: true
      text: "Tande's Shop"
      url: "https://tandechen.github.io/shop"
    show_search: true
    show_theme_chooser: true

# Localization
locale:
  date_format: 'Jan 2, 2024'
  time_format: '3:04 PM'
